### ISSUE TITLE
Lauffähiger Code?

### ISSUE THREAD

**Issue by impl25** [gematik/lib-vau#16]
Liebes Softwareteam,

ist dieser Code out of the box lauffähig?
Ich bekomme recht viele Fehler, wenn ich den Source Code in meine IDE importiere.

Falls der Code bei Ihnen lauffähig ist, würde es mich interessieren, welches JDK 17 Sie verwenden, welche IDE etc.

Ein ganz einfacher nachvollziehbarer Fehler ist in der Klasse `VauClientStateMachine`:
`The type VauClientStateMachine must implement the inherited abstract method AbstractVauStateMachine.getRequestCounter()`

In `AbstractVauStateMachine` selbst ist bspw. der Fehler:
`log cannot be resolved`

Vielleicht liegt auch der Fehler auf meiner Seite aber gerade bei letzterem Fehler kann ich nicht erkennen, wo sich das Objekt log befinden soll.

**Comment by impl25** [comment]
Danke für den Hinweis.
Für alle die Lombok noch einrichten müssen hier eine Mögliche Hilfestellung:
https://www.baeldung.com/lombok-ide

@sonerd noch eine kurze Frage. Ist es angedacht, die Beispielimplementierung zu erweitern, bspw. für die von Ihnen dankenswerterweise zur Verfügung gestellten Dockerfiles?
https://github.com/gematik/epa-deployment
Das wäre doch eine geniale Sache beide Komponenten im Einklang zu erleben, oder?

**Comment by sonerd** [comment]
@impl25 genau im https://github.com/gematik/epa-deployment wird lib-vau genutzt, um den VAU-Handshake durchzuführen.

**Comment by impl25** [comment]
Vielen Dank
