### ISSUE TITLE
lib-vau für ePA 3.0 in DiGAs

### ISSUE THREAD

**Issue by thomasrichner-oviva** [gematik/lib-vau#18]
Hallo zusammen,

Ich probiere gerade die Lücken zu füllen zwischen der [DiGA ePA implementation](https://github.com/oviva-ag/diga-epa-lib ) und der lib-vau.

Es scheint https://github.com/gematik/ref-ePA-vauchannel ist nicht mehr so ganz up-to-date.

Gibts irgendwo noch eine Referenz wie ich 'lib-vau' mit z.B. 'Apache CXF' verbinde?

lg

**Comment by Arkinator** [comment]
Moin!

Die dort hinterlegte VAU ist die für die EPA 1 und 2. Für EPA 3 (und auch für das ERezept) gibt es ein komplett anderes Protokoll. Diese Library hier implementiert die VAU für die EPA-für-alle (EPA 3). Eine CXF-Integration gibt es nicht.

Viele Grüße

**Comment by thomasrichner-oviva** [comment]
Hey @Arkinator ,

Danke schonmal!

Ich habe ein komplettes RU & PU setup mit SMC-Bs und möchte jetzt mit der neuen ePA 3.0 gegen die RU testen. Der use-case ist schreiben von Dokumente in die ePA.

Wo finde ich denn die nötigen Komponenten?
Soweit ich sehe gibt es irgendwo ein proxy-server ( https://hub.docker.com/r/gematik1/epa-vau-proxy-server ) ich kann jedoch die sources dazu nicht finden.

Viele Grüße, Thomas

**Comment by fnoGematik** [comment]
Hallo @thomasrichner-oviva ,

für die Unterstützung der Entwicklung des Primärsystems für "ePA für alle" (ePA 3.0) haben wir auch Mock Services und eine kleine Testsuite (PS-Testsuite) bereitgestellt, welche in ihrer Umgebung per Docker gestartet werden können.

https://github.com/gematik/epa-deployment

Dort ist auch ein Mock Service für die VAU Instanz enthalten, welche wiederum die lib-vau nutzt, um den VAU Handshake durchzuführen sowie auch Nutzerdaten zu ent-/verschlüsseln.

Wenn sie gegen die Aktensysteme der RU-DEV Umgebung testen wollen, können sie das bereits machen.
Die Aktensysteme sind unter den folgenden DNS über den Konnektor in der TI erreichbar.

- epa-as-1.dev.epa4all.de
- epa-as-2.dev.epa4all.de

Viele Grüße,
